name: test

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: test
    runs-on: macos-12

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: test
        env:
          scheme: ${{ 'ground-list-up' }}
        run: |
          pod install
          xcodebuild -scheme "$scheme" -workspace "$scheme".xcworkspace -sdk $target_sdk
