name: test

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: test
    runs-on: macos-12

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: test
        env:
          scheme: ${{ 'ground-list-up' }}
        run: |
          pod install
          xcodebuild test -project "$scheme".xcodeproj/ -scheme "$scheme" -resultBundlePath TestResults -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 8"
          # xcodebuild -workspace "$scheme".xcworkspace -scheme "$scheme" "test" "-destination" "id=FC628398-B173-431B-A25B-3E42F3D2878C"
