name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: test
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and Test
        env:
          scheme: ${{ 'ground-list-up' }}
          platform: ${{ 'iOS Simulator' }}
          target_device: ${{ 'iPhone 14' }}
          target_sdk: ${{ 'iphonesimulator' }}
        run: |
          pod install
          xcodebuild -scheme "$scheme" -workspace "$scheme".xcworkspace -sdk $target_sdk
          # xcodebuild -scheme "$scheme" -workspace "$scheme".xcworkspace -sdk $target_sdk -destination 'platform=$platform,name=$target_device' clean test
