name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: test
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache CocoaPods files
        uses: actions/cache@preview
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - name: Build
        env:
          scheme: ${{ 'ground-list-up' }}
          platform: ${{ 'iOS Simulator' }}
          target_device: ${{ 'iPhone 14' }}
          target_sdk: ${{ 'iphonesimulator' }}
        run: |
          pod install
          xcodebuild -scheme "$scheme" -workspace "$scheme".xcworkspace -sdk $target_sdk
