name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: test
    runs-on: macos-12

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache CocoaPods files
        uses: actions/cache@preview
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - name: Build
        env:
          scheme: ${{ 'ground-list-up' }}
        run: |
          pod install
          xcodebuild -workspace "$scheme".xcworkspace -scheme "$scheme" "test" "-destination" "id=FC628398-B173-431B-A25B-3E42F3D2878C"
