name: test

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  id-token: write

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build and Test
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-xcode@v2
      with:
        xcode-version: 11.4
    - run: xcodebuild clean build test -workspace ground-list-up.xcworkspace -scheme ground-list-up -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest'
