name: test

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  id-token: write

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Test
        run: xcodebuild test -project ground-list-up.xcodeproj/ -scheme XCTestExample -resultBundlePath TestResults -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 14"


      - uses: kishikawakatsumi/xcresulttool@v1.3.0
        with:
          path: TestResults.xcresult
        if: success() || failure()
