name: test

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  id-token: write

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: swift test
